name: 'Backup DB'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

env:
  SITE_IP: 94.237.119.58
  SITE_USER: root
  SITE_DB: rks
  SITE_BUCKET: gs://rissola-backups

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SITE_IP >> ~/.ssh/known_hosts
      - name: Backup RKS database
        run: |
          # Create timestamp
          TIMESTAMP=$(date +%Y-%m-%d-%H:%M)
          # Create backup file
          ssh -i ~/.ssh/id_rsa $SITE_USER@$SITE_IP "dokku mariadb:export $SITE_DB" > /tmp/backup.sql
          # Compress the file
          gzip /tmp/backup.sql
          # Upload to GCS
          gsutil -q cp /tmp/backup.sql.gz $SITE_BUCKET/rks_${TIMESTAMP}.sql.gz
          # Cleanup
          rm /tmp/backup.sql.gz
